platform :ios, '10.0'
use_frameworks!

target 'ECDHESSwift_Example' do
  pod 'ECDHESSwift', :path => '../'
  pod 'JOSESwift', '~> 1.8.1'
  pod 'CryptoSwift', '~> 1.4.1'

  target 'ECDHESSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble', '~> 9.2.0'
    pod 'Quick', '~> 2.0.0'
  end
end
